export const PERMISSIONS = {
  PLATFORM_READ: 'platform:read',
  PLATFORM_WRITE: 'platform:write',
  TENANTS_READ: 'tenants:read',
  TENANTS_WRITE: 'tenants:write',
  PLANS_READ: 'plans:read',
  PLANS_WRITE: 'plans:write',
  USERS_READ: 'users:read',
  USERS_WRITE: 'users:write',
  PRODUCTS_READ: 'products:read',
  PRODUCTS_WRITE: 'products:write',
  INVENTORY_READ: 'inventory:read',
  INVENTORY_WRITE: 'inventory:write',
  WAREHOUSES_READ: 'warehouses:read',
  WAREHOUSES_WRITE: 'warehouses:write',
  PURCHASES_READ: 'purchases:read',
  PURCHASES_WRITE: 'purchases:write',
  CUSTOMERS_READ: 'customers:read',
  CUSTOMERS_WRITE: 'customers:write',
  ORDERS_READ: 'orders:read',
  ORDERS_WRITE: 'orders:write',
  ORDERS_PACK: 'orders:pack',
  ORDERS_DISPATCH: 'orders:dispatch',
  PAYMENTS_READ: 'payments:read',
  PAYMENTS_WRITE: 'payments:write',
  REPORTS_READ: 'reports:read',
  REPORTS_GST: 'reports:gst',
  INTEGRATIONS_READ: 'integrations:read',
  INTEGRATIONS_WRITE: 'integrations:write',
  SETTINGS_READ: 'settings:read',
  SETTINGS_WRITE: 'settings:write',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
