export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  SALES_STAFF: 'SALES_STAFF',
  PACKING_STAFF: 'PACKING_STAFF',
  DISPATCH_STAFF: 'DISPATCH_STAFF',
  ACCOUNTANT: 'ACCOUNTANT',
} as const;

export type SystemRole = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

export const TENANT_STAFF_ROLES: SystemRole[] = [
  SYSTEM_ROLES.COMPANY_ADMIN,
  SYSTEM_ROLES.INVENTORY_MANAGER,
  SYSTEM_ROLES.SALES_STAFF,
  SYSTEM_ROLES.PACKING_STAFF,
  SYSTEM_ROLES.DISPATCH_STAFF,
  SYSTEM_ROLES.ACCOUNTANT,
];
